== Setup
To run the code in Android Studio, the following build parameters need to be setup in your local `gradle.properties` file.

=== AWS Product Advertising API
The app uses AWS Product advertising API to get the details of the upcoming releases.

URL : http://docs.aws.amazon.com/AWSECommerceService/latest/DG/becomingDev.html

Properties to be added the gradle properties are:

* `AwsCustKey="<aws-customer-key>"`
* `AwsApiKey="<aws-api-key>"`

=== Goodreads API
The app uses Goodreads API to find author and book related information
URL : https://www.goodreads.com/api

Property to be added the gradle properties are:

`GrApiKey="<gr-api-key>"`

=== Google Services Configuration - Identity and Analytics
The app uses Google Play services to perform Google Identity Signin and use Google Analytics to track user activity. Generate a `google-services.json` file for your android debug key including both Signin and Analytics.
Follow the instructions from https://developers.google.com/identity/sign-in/android/start-integrating. The package name to be used is `com.capstone.authorfollow`

=== Verifying Google Analytics Execution
Refer to https://developers.google.com/analytics/devguides/collection/android/v4/ for more details

Use these commands to track the Analytics Events and hits being sent

* `adb shell setprop log.tag.GAv4 DEBUG`
* `adb logcat -s GAv4`


== About the App

=== Introduction
An avid book reader is always on the lookout for new releases especially from the authors that they love. However, there is no such tool today which informs you about upcoming releases. “Author Follow” allows you to keep tabs on upcoming and recent releases of your favorite book authors, search for new authors and more. This app uses Amazon’s product release API to scour for their favorite authors’ publications.

=== Libraries
* App Compat Libraries
* ButterKnife
* Retrofit
* CircleImageView
* SimpleXml
* Picasso
* ActiveAndroid
* Google Analytics and Auth

=== Screenshots
Screenshots of the app on phone and tablet are available in the screens folder

=== Release version/Installable
Available under app-release folder

=== Screencast
_TBD_
